import {FormEvent,useEffect,useRef,useState} from 'react';
import {lastProject} from './projectSession';
import ResearchWorkflowPanel from './ResearchWorkflowPanel';
import {teamApi,teamIntent,Team,RigSpec,Snapshot,Harness,Event,Permission,Device} from './teamApi';

export default function MultiAgentSettingsPage(){
  const [token,setToken]=useState(''),[connected,setConnected]=useState(false),[identity,setIdentity]=useState<{id:string;scopes:string[];rig_ids:string[]}|null>(null);
  const [teams,setTeams]=useState<Team[]>([]),[harnesses,setHarnesses]=useState<Harness[]>([]),[templates,setTemplates]=useState<RigSpec[]>([]);
  const [selected,setSelected]=useState(new URLSearchParams(location.search).get('team')||''),[team,setTeam]=useState<Snapshot|null>(null),[seat,setSeat]=useState('');
  const [events,setEvents]=useState<Event[]>([]),[permissions,setPermissions]=useState<Permission[]>([]),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
  const [connectionError,setConnectionError]=useState('');
  const [newName,setNewName]=useState(''),[newId,setNewId]=useState(''),[template,setTemplate]=useState('research'),[newProject,setNewProject]=useState(lastProject()||'');
  const [projects,setProjects]=useState<{id:string;name:string}[]>([]),[pairResearch,setPairResearch]=useState(false);
  const [instruction,setInstruction]=useState(''),[mode,setMode]=useState('workflow'),[resume,setResume]=useState(''),[fork,setFork]=useState(false);
  const [sender,setSender]=useState(''),[recipient,setRecipient]=useState('*'),[message,setMessage]=useState(''),[messages,setMessages]=useState<{id:number;sender:string;recipient:string;body:string}[]>([]);
  const [files,setFiles]=useState<{path:string;bytes:number}[]>([]),[file,setFile]=useState<{path:string;content:string;sha256:string|null}|null>(null),[review,setReview]=useState<{diff:string;log:string;status:string}|null>(null);
  const [devices,setDevices]=useState<Device[]>([]),[pair,setPair]=useState<{pairing_id:string;code:string;expires_at:string}|null>(null),[pairingId,setPairingId]=useState(''),[pairCode,setPairCode]=useState(''),[deviceName,setDeviceName]=useState('Personal device');
  const [showSeatConfig,setShowSeatConfig]=useState(false);
  const [specText,setSpecText]=useState(''),[showSpec,setShowSpec]=useState(false),[snapshotList,setSnapshotList]=useState<{id:string;created_at:string}[]>([]);
  const [terminalArgv,setTerminalArgv]=useState('["python", "-m", "pytest", "tests", "-q"]'),[terminalOutput,setTerminalOutput]=useState('');
  const [contextId,setContextId]=useState(''),[contextKind,setContextKind]=useState('library'),[contextPath,setContextPath]=useState('');
  const [bundleText,setBundleText]=useState(''),[importId,setImportId]=useState(''),[usage,setUsage]=useState<unknown>(null);
  const [runId,setRunId]=useState(''),[binding,setBinding]=useState<Record<string,unknown>|null>(null),[reviewTask,setReviewTask]=useState(''),[researchTtl,setResearchTtl]=useState(600),[researchAccount,setResearchAccount]=useState('');
  const [researchCommands,setResearchCommands]=useState<{request_id:string;state:string;binding:{project_id:string;run_id:string};run:{state:string}}[]>([]);
  const [agentCredential,setAgentCredential]=useState('');
  const [modelDrafts,setModelDrafts]=useState<Record<string,string>>({});
  const [harnessJson,setHarnessJson]=useState('{"id":"local-acp","kind":"acp","executable":"","args":[],"protocol_version":1,"models":[],"enabled":true}');
  const [resourceJson,setResourceJson]=useState('{"id":"coding-pool","name":"Coding pool","seat_ids":["builder","qa"],"max_parallel":1}');
  const [resources,setResources]=useState<{id:string;name:string;max_parallel:number;seat_ids:string[]}[]>([]);
  const [slackChannel,setSlackChannel]=useState(''),[slackEnabled,setSlackEnabled]=useState(false),[slackText,setSlackText]=useState('');
  const cursor=useRef(0),polling=useRef(false),current=useRef(selected);
  const admin=identity?.scopes.includes('admin'), can=(scope:string)=>admin||identity?.scopes.includes(scope);
  const call=<T,>(path:string,method='GET',body?:unknown)=>teamApi<T>(path,token,method,body);
  async function action(work:()=>Promise<void>){setBusy(true);setError('');setNotice('');try{await work();}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}}
  async function connect(){const who=await call<NonNullable<typeof identity>&{csrf?:string}>('/identity');if(who.csrf)sessionStorage.setItem('agent-csrf',who.csrf);setIdentity(who);setConnected(true);await loadCatalog();}
  async function loadCatalog(){const [rows,hs,ts]=await Promise.all([call<Team[]>('/teams'),call<Harness[]>('/harnesses'),call<RigSpec[]>('/templates')]);setTeams(rows);setHarnesses(hs);setTemplates(ts);setSelected(old=>rows.some(r=>r.id===old)?old:rows[0]?.id||'');if(identity?.scopes.includes('admin')||token) setProjects(await call('/workflow-projects'));}
  async function refresh(id=selected){if(!id||polling.current)return;polling.current=true;try{
    const [value,log,ps,ms]=await Promise.all([call<Snapshot>('/teams/'+id),call<Event[]>('/teams/'+id+'/events?after='+cursor.current),call<Permission[]>('/teams/'+id+'/permissions'),call<typeof messages>('/teams/'+id+'/messages')]);
    if(current.current!==id)return;
    setConnectionError('');
    setTeam(value);setSeat(old=>value.spec.seats.some(s=>s.id===old)?old:value.spec.seats[0]?.id||'');setSender(old=>value.spec.seats.some(s=>s.id===old)?old:value.spec.seats[0]?.id||'');
    if(log.length){cursor.current=log[log.length-1].id;setEvents(old=>[...old,...log].slice(-300));}setPermissions(ps);setMessages(ms);
  }finally{polling.current=false;}}
  useEffect(()=>{current.current=selected;cursor.current=0;setEvents([]);setTeam(null);setFiles([]);setFile(null);setReview(null);setModelDrafts({});setSnapshotList([]);
    if(!connected||!selected)return;let stopped=false;
    const update=()=>void refresh(selected).catch(e=>{if(!stopped)setConnectionError(String(e.message||e));});update();void call<typeof snapshotList>('/teams/'+selected+'/snapshots').then(rows=>{if(!stopped)setSnapshotList(rows);}).catch(()=>{});const timer=setInterval(update,2000);
    const url=new URL(location.href);url.searchParams.set('team',selected);history.replaceState(null,'',url);
    return()=>{stopped=true;clearInterval(timer);};},[selected,connected,token]);
  useEffect(()=>{setFile(null);setFiles([]);setReview(null);},[seat]);
  useEffect(()=>{void connect().catch(()=>{});},[]);
  const path='/teams/'+selected,seatPath=path+'/seats/'+seat;
  const codingWorkflow=Boolean(team&&['lead','builder','qa','reviewer'].every(role=>team.spec.seats.some(s=>s.id===role)));
  const activeSeat=team?.spec.seats.find(s=>s.id===seat), seatState=team?.seats.find(s=>s.id===seat)?.state;
  async function create(e:FormEvent){e.preventDefault();await action(async()=>{
    const source=templates.find(t=>t.template===template);if(!source)throw new Error('Chọn team template');
    const spec={...source,name:newName,project_id:newProject||null};
    await call('/teams','POST',{id:newId,spec});await loadCatalog();setSelected(newId);setNewName('');setNewId('');setNotice('Đã tạo team. Cấu hình harness và quyền từng seat trước khi chạy.');
  });}
  async function updateSeat(id:string,key:string,value:unknown){if(!team)return;const spec={...team.spec,seats:team.spec.seats.map(s=>s.id===id?{...s,[key]:value,...(key==='harness'?{model:harnesses.find(h=>h.spec.id===value)?.spec.models[0]||null}:{})}:s)};await call(path,'PUT',{spec,revision:team.revision});await refresh();}
  const backProject=lastProject();
  return <><aside className="rail settings-rail"><a className="brand" href="/" style={{textDecoration:'none'}}><span className="brand-mark">∿</span><span>AI SCIENTIST<small>LOCAL WORKBENCH</small></span></a>
    <a href={backProject?`/?project=${backProject}`:'/'}>← Quay về Workbench</a><nav className="settings-nav" aria-label="Settings"><a href="/?page=settings&tab=kaggle-proxy">Kaggle proxy</a><a className="active" href="/?page=settings&tab=multi-agent" aria-current="page">Multi-agent</a></nav>
    <div className="rail-footer">Pipeline research và phiên agent.<br/>{connected?identity?.id:'Chưa kết nối'}</div></aside>
  <main className="settings-page team-settings"><header><div><span className="eyebrow">SETTINGS</span><h1>Multi-agent</h1><p className="muted">Cấu hình từng giai đoạn research, theo dõi agent và điều khiển từ xa.</p></div>{connected&&<button disabled={busy} onClick={()=>void action(async()=>{await call('/logout','POST');sessionStorage.removeItem('agent-csrf');setToken('');setIdentity(null);setConnected(false);setTeam(null);setTeams([]);})}>Đăng xuất</button>}</header>
    {(error||connectionError)&&<p role="alert" className="alert error">{error||connectionError}</p>}{notice&&<p role="status" className="alert">{notice}</p>}
    {!connected?<section className="panel"><h2>Kết nối quản lý agent</h2><p>Nhập control token được cấu hình khi khởi động Workbench, hoặc ghép cặp thiết bị bằng mã từ máy chính.</p>
      <form className="stack" onSubmit={e=>{e.preventDefault();void action(connect);}}><label>Control token<input type="password" autoComplete="off" value={token} onChange={e=>setToken(e.target.value)}/></label><button className="primary" disabled={busy}>Kết nối</button></form>
      <details><summary>Ghép cặp thiết bị</summary><form className="stack" onSubmit={e=>{e.preventDefault();void action(async()=>{const result=await teamApi<{csrf:string}>('/pair/exchange','','POST',{pairing_id:pairingId,code:pairCode,name:deviceName});sessionStorage.setItem('agent-csrf',result.csrf);setToken('');await teamApi('/identity');setConnected(true);const who=await teamApi<NonNullable<typeof identity>>('/identity');setIdentity(who);await loadCatalog();});}}>
        <label>Pairing ID<input required value={pairingId} onChange={e=>setPairingId(e.target.value)}/></label><label>Mã ghép cặp<input type="password" required value={pairCode} onChange={e=>setPairCode(e.target.value)}/></label><label>Tên thiết bị<input required value={deviceName} onChange={e=>setDeviceName(e.target.value)}/></label><button disabled={busy}>Ghép cặp</button></form></details>
    </section>:<>
    <section className="panel"><div className="panel-head"><h2>Teams</h2><div className="actions"><button disabled={busy} onClick={()=>void action(loadCatalog)}>Làm mới</button>{admin&&<button disabled={busy} onClick={()=>void action(async()=>{await call('/harnesses/dsh/import','POST');await loadCatalog();setNotice('Đã copy provider/model từ DSH local vào cấu hình riêng của repo.');})}>Import DSH ACP</button>}</div></div>
      <div className="team-selector">{teams.map(t=><button key={t.id} aria-pressed={selected===t.id} onClick={()=>setSelected(t.id)}>{t.spec.name}<small>{t.enabled?'Đang chạy':'Tạm dừng'} · {t.spec.seats.length} seats</small></button>)}</div>
      {admin&&<details><summary>Tạo team mới</summary><form className="team-create" onSubmit={e=>void create(e)}><label>Team ID<input required pattern="[A-Za-z][A-Za-z0-9_-]{0,63}" value={newId} onChange={e=>setNewId(e.target.value)}/></label><label>Tên team<input required maxLength={120} value={newName} onChange={e=>setNewName(e.target.value)}/></label><label>Template<select value={template} onChange={e=>setTemplate(e.target.value)}>{templates.map(t=><option key={t.template} value={t.template||''}>{t.name}</option>)}</select></label><label>Project<select value={newProject} onChange={e=>setNewProject(e.target.value)}><option value="">Không gắn project</option>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><button className="primary" disabled={busy}>Tạo team</button></form></details>}
      {admin&&<details><summary>Cấu hình harness local / ACP</summary><p className="muted">Chọn runtime đã cài và model catalog. Cấu hình này chỉ lưu trên máy backend.</p><button disabled={busy} onClick={()=>void action(async()=>setHarnessJson(JSON.stringify(await call('/harnesses?details=true'),null,2)))}>Xem cấu hình hiện có</button><label>HarnessSpec JSON<textarea className="team-code" rows={8} value={harnessJson} onChange={e=>setHarnessJson(e.target.value)}/></label><button disabled={busy} onClick={()=>void action(async()=>{const spec=JSON.parse(harnessJson);if(Array.isArray(spec))throw new Error('Chọn một HarnessSpec để lưu');await call('/harnesses/'+encodeURIComponent(spec.id),'PUT',spec);await loadCatalog();setNotice('Đã lưu harness local');})}>Lưu harness</button><details><summary>Capabilities</summary><pre>{JSON.stringify(harnesses,null,2)}</pre></details></details>}
      {admin&&<details><summary>Import / export team bundle</summary><p className="muted">Bundle chỉ chứa RigSpec và harness identity/model. Cấu hình executable, credentials và dữ liệu Library được thiết lập riêng trên máy đích.</p><label>Team ID để import<input value={importId} onChange={e=>setImportId(e.target.value)}/></label><label>Bundle JSON<textarea className="team-code" rows={8} value={bundleText} onChange={e=>setBundleText(e.target.value)}/></label><div className="actions"><button disabled={busy||!selected} onClick={()=>void action(async()=>setBundleText(JSON.stringify(await call(path+'/bundle'),null,2)))}>Export team đã chọn</button><button disabled={busy||!importId||!bundleText} onClick={()=>void action(async()=>{await call('/bundles','POST',{id:importId,bundle:JSON.parse(bundleText)});await loadCatalog();setSelected(importId);})}>Import</button></div></details>}
      {!teams.length&&<p className="empty">Chưa có team.</p>}
    </section>
    {team&&<><ResearchWorkflowPanel team={team} harnesses={harnesses} canResearch={Boolean(can('research'))} call={call} updateSeat={updateSeat} onSelectSeat={id=>{setSeat(id);}} canConfigureAgents={Boolean(admin)}/><details className="panel" open={showSeatConfig} onToggle={e=>setShowSeatConfig(e.currentTarget.open)}><summary>Cấu hình team và workspace của từng agent</summary><section className="panel"><div className="panel-head"><h2>{team.spec.name}</h2><div className="actions"><span className="state-tag">{team.enabled?'RUNNING':'PAUSED'}</span>{can('task')&&<><button className="primary" disabled={busy||Boolean(team.enabled)} onClick={()=>void action(async()=>{await call(path+'/start','POST');await refresh();})}>Bắt đầu</button><button disabled={busy||!team.enabled} onClick={()=>void action(async()=>{await call(path+'/pause?interrupt=true','POST');await refresh();})}>Dừng team</button></>}</div></div>
      {team.spec.project_id&&<p><a href={'/?project='+team.spec.project_id}>Mở project ↗</a></p>}
      <div className="team-topology" role="img" aria-label="Team topology"><svg viewBox={`0 0 ${Math.max(600,team.spec.seats.length*160)} 130`}><line x1="80" y1="65" x2={Math.max(520,team.spec.seats.length*160-80)} y2="65" stroke="currentColor"/>{team.spec.seats.map((s,i)=><g key={s.id} transform={`translate(${i*160+20},20)`}><rect width="120" height="90" rx="8" fill="var(--panel2)" stroke={seat===s.id?'var(--mint)':'var(--line)'}/><text x="60" y="28" textAnchor="middle">{s.id}</text><text x="60" y="51" textAnchor="middle" className="muted">{s.role}</text><text x="60" y="73" textAnchor="middle" className="muted">{s.pod}</text></g>)}</svg></div>
      <div className="team-seats">{team.spec.seats.map(s=>{const hs=harnesses.find(h=>h.spec.id===s.harness);return <article key={s.id} className={seat===s.id?'selected':''}>
        <button className="team-seat-title" onClick={()=>setSeat(s.id)} aria-pressed={seat===s.id}>{s.id}<small>{s.role} · {team.seats.find(v=>v.id===s.id)?.state||'IDLE'}</small></button>
        <label>Harness<select aria-label={'Harness '+s.id} value={s.harness} disabled={busy||!admin} onChange={e=>void action(()=>updateSeat(s.id,'harness',e.target.value))}>{harnesses.map(h=><option key={h.spec.id} value={h.spec.id}>{h.spec.id} · {h.spec.kind}</option>)}</select></label>
        <label>Model<input aria-label={'Model '+s.id} list={'models-'+s.id} value={modelDrafts[s.id]??s.model??''} placeholder="Provider default" disabled={busy||!admin||Boolean(team.enabled)} onChange={e=>setModelDrafts(old=>({...old,[s.id]:e.target.value}))} onBlur={()=>{if(modelDrafts[s.id]===undefined)return;void action(async()=>{await updateSeat(s.id,'model',modelDrafts[s.id]||null);setModelDrafts(old=>{const next={...old};delete next[s.id];return next;});});}}/><datalist id={'models-'+s.id}>{hs?.spec.models.map(m=><option key={m} value={m}/>)}</datalist></label>
        <p className="muted">{hs?.probe.ready?'CLI sẵn sàng':'CLI chưa sẵn sàng'}{hs?.probe.attention_required?' · '+hs.probe.attention_required:''}</p>
        <div className="team-policy">{(['file_edits','terminal','network'] as const).map(key=><label key={key}><input type="checkbox" checked={s.policy[key]} disabled={busy||!admin} onChange={e=>void action(()=>updateSeat(s.id,'policy',{...s.policy,[key]:e.target.checked}))}/>{key==='file_edits'?'Sửa file':key==='terminal'?'Terminal':'Network'}</label>)}</div>
        {can('task')&&<button disabled={busy||team.seats.find(v=>v.id===s.id)?.state!=='BUSY'} onClick={()=>void action(async()=>{await call(path+'/seats/'+s.id+'/interrupt','POST');})}>Interrupt</button>}
      </article>;})}</div>
      {admin&&<details open={showSpec} onToggle={e=>setShowSpec(e.currentTarget.open)}><summary onClick={()=>{if(!showSpec)setSpecText(JSON.stringify(team.spec,null,2));}}>Topology, context và giới hạn</summary><p className="muted">Thêm/bớt seat, pod, allowed_paths hoặc context reference trong RigSpec. Cần giải quyết task còn chờ/đang chạy trước khi lưu.</p><textarea className="team-code" aria-label="RigSpec" rows={14} value={specText} onChange={e=>setSpecText(e.target.value)}/><button disabled={busy} onClick={()=>void action(async()=>{await call(path,'PUT',{spec:JSON.parse(specText),revision:team.revision});await refresh();})}>Lưu cấu hình team</button></details>}
    </section></details>
    {can('task')&&<section className="panel"><h2>Giao việc</h2><form className="stack" onSubmit={e=>{e.preventDefault();void action(async()=>{const body=mode==='workflow'&&codingWorkflow?{instruction}:{seat,task:{instruction,kind:'coding',resume_session:resume||null,fork_session:fork}};const intent=await teamIntent(selected+':'+mode,body);await call(path+(mode==='workflow'&&codingWorkflow?'/workflow':'/tasks'),'POST',{...body,request_id:intent.id});intent.ack();setInstruction('');await refresh();setNotice('Đã xếp task. Bấm Bắt đầu nếu team đang tạm dừng.');});}}>
      <label>Luồng<select value={codingWorkflow?mode:"single"} onChange={e=>setMode(e.target.value)}>{codingWorkflow&&<option value="workflow">Lead → Builder → QA → Reviewer</option>}<option value="single">Task cho seat đang chọn</option></select></label>
      <label>Yêu cầu<textarea required rows={4} value={instruction} onChange={e=>setInstruction(e.target.value)} maxLength={70000}/></label>
      {(mode==='single'||!codingWorkflow)&&<><label>Resume session<select value={resume} onChange={e=>setResume(e.target.value)}><option value="">Phiên mới</option>{team.sessions.filter(s=>s.seat_id===seat&&s.stop_receipt?.tree_stopped&&s.provider_session).map(s=><option key={s.id} value={s.id}>{s.id} · {s.state}</option>)}</select></label><label><input type="checkbox" checked={fork} onChange={e=>setFork(e.target.checked)}/>Fork (harness có hỗ trợ)</label></>}
      <button className="primary" disabled={busy}>Giao việc</button></form></section>}
    <section className="panel"><h2>Tasks & sessions</h2><div className="team-tasks">{team.tasks.map(t=><article key={t.id}><div className="panel-head"><strong>{t.seat}</strong><span className="state-tag">{t.state}</span></div><small>{t.request_id}</small><p>{(t.payload.instruction||t.payload.argv?.join(' ')||'').slice(0,260)}</p>{t.result?.summary&&<p>{t.result.summary}</p>}{t.result?.error&&<p className="alert error">{t.result.error}</p>}{t.result?.checks?.map((check,i)=><p key={i}>{check}</p>)}{t.result?.checkpoint&&<code>{t.result.checkpoint}</code>}{t.state==='PENDING'&&can('task')&&<button disabled={busy} onClick={()=>void action(async()=>{await call(path+'/tasks/'+t.id,'DELETE');await refresh();})}>Hủy task chờ</button>}</article>)}</div>
      {!team.tasks.length&&<p className="empty">Chưa có task.</p>}
      {can('task')&&team.tasks.filter(t=>['FAILED','CANCELLED'].includes(t.state)).map(t=><p key={'retry-'+t.id}>{t.seat} · {t.state} <button disabled={busy||Boolean(team.enabled)} onClick={()=>void action(async()=>{const result=await call<{output?:string}>(path+'/tasks/'+t.id+'/retry','POST');if(result.output)setTerminalOutput(result.output);await refresh();setNotice('Đã yêu cầu retry sau khi xác minh phiên trước dừng.');})}>Retry task này</button></p>)}
      {team.sessions.map(s=><details key={s.id}><summary>{s.seat_id} · {s.provider_id} · {s.state} · {s.id.slice(0,10)}</summary><pre>{JSON.stringify({session:s.provider_session,usage:s.usage,stop_receipt:s.stop_receipt},null,2)}</pre>{s.state==='UNKNOWN'&&can('task')&&<div className="actions"><button disabled={busy} onClick={()=>void action(async()=>{await call(path+'/sessions/'+s.id+'/reconcile','POST');await refresh();})}>Xác minh đã dừng</button><button disabled={busy} onClick={()=>void action(async()=>{await call(path+'/sessions/'+s.id+'/reconcile?retry=true','POST');await refresh();})}>Xác minh rồi retry</button></div>}</details>)}
    </section>
    {permissions.length>0&&<section className="panel"><h2>Quyền đang chờ duyệt</h2>{permissions.map(p=><article key={p.id}><pre>{JSON.stringify(p.operation,null,2)}</pre>{can('permission')&&p.operation.options?.filter(o=>['allow_once','reject_once'].includes(o.kind)).map(o=><button key={o.optionId} disabled={busy} onClick={()=>void action(async()=>{await call(path+'/permissions/'+p.id,'POST',{option_id:o.optionId});await refresh();})}>{o.name}</button>)}</article>)}</section>}
    <section className="panel"><div className="panel-head"><h2>Workspace · {seat}</h2><div className="actions"><button disabled={busy} onClick={()=>void action(async()=>{setFiles(await call(seatPath+'/files'));setReview(await call(seatPath+'/review'));})}>Đọc files / diff</button>{can('workspace')&&<button disabled={busy||seatState==='BUSY'||seatState==='UNKNOWN'} onClick={()=>void action(async()=>{await call(path+'/snapshots','POST');setSnapshotList(await call(path+'/snapshots'));setNotice('Đã lưu snapshot');})}>Lưu snapshot</button>}</div></div>
      <div className="team-editor"><div className="team-file-list">{files.map(f=><button key={f.path} onClick={()=>void action(async()=>setFile(await call(seatPath+'/file?path='+encodeURIComponent(f.path))))}>{f.path}</button>)}</div><div>{file?<><label>{file.path}<textarea className="team-code" rows={18} value={file.content} readOnly={!can('workspace')||!activeSeat?.policy.file_edits} onChange={e=>setFile({...file,content:e.target.value})}/></label><button disabled={busy||!can('workspace')||!activeSeat?.policy.file_edits||seatState==='BUSY'||seatState==='UNKNOWN'} onClick={()=>void action(async()=>{setFile(await call(seatPath+'/file','PUT',file));setReview(await call(seatPath+'/review'));})}>Lưu & checkpoint</button></>:<p className="muted">Chọn file để xem code.</p>}</div></div>
      {review&&<details open><summary>Git diff & history</summary><pre className="team-code">{review.diff||'Không có khác biệt so với base.'}</pre><pre>{review.log}</pre></details>}
      {can('workspace')&&<details><summary>Terminal</summary><p className="muted">Chạy lệnh trong OS sandbox của seat. Quyền ghi file và network tuân theo policy ở trên; thời hạn 30 giây.</p><form className="stack" onSubmit={e=>{e.preventDefault();void action(async()=>{const body={argv:JSON.parse(terminalArgv)};const intent=await teamIntent(selected+':terminal:'+seat,body);const result=await call<{output?:string;error?:string}>(seatPath+'/terminal','POST',{...body,request_id:intent.id});intent.ack();setTerminalOutput((result.error?result.error+'\n':'')+(result.output||''));await refresh();});}}><label>Lệnh (argv JSON)<textarea rows={2} value={terminalArgv} onChange={e=>setTerminalArgv(e.target.value)}/></label><button disabled={busy||!activeSeat?.policy.terminal||seatState==='BUSY'||seatState==='UNKNOWN'}>Chạy lệnh</button></form><pre role="log">{terminalOutput||'Chưa chạy lệnh.'}</pre></details>}
      {snapshotList.map(s=><p key={s.id}>{s.created_at} <button disabled={busy||Boolean(team.enabled)||!can('workspace')} onClick={()=>void action(async()=>{await call(path+'/snapshots/'+s.id+'/restore','POST');await refresh();})}>Khôi phục snapshot</button></p>)}
    </section>
    <section className="panel"><h2>Context, skills & rosters</h2><p className="muted">Nguồn được pin version/hash và chỉ gửi tới các seat được chọn. Library lấy từ project đã gắn với team.</p><pre>{JSON.stringify(team.spec.context,null,2)}</pre>{can('workspace')&&<form className="team-create" onSubmit={e=>{e.preventDefault();void action(async()=>{await call(path+'/context','POST',{id:contextId,kind:contextKind,path:contextPath,seats:[seat]});await refresh();setContextId('');setContextPath('');});}}><label>Context ID<input required value={contextId} onChange={e=>setContextId(e.target.value)}/></label><label>Loại<select value={contextKind} onChange={e=>setContextKind(e.target.value)}>{['library','source','skill','knowledge','roster'].map(k=><option key={k}>{k}</option>)}</select></label><label>{contextKind==='library'?'Library resource ID':'Đường dẫn file tracked trong repo'}<input required value={contextPath} onChange={e=>setContextPath(e.target.value)}/></label><button disabled={busy}>Pin cho {seat}</button></form>}</section>
    {team.spec.project_id&&can('research')&&<section className="panel"><div className="panel-head"><h2>Research bridge</h2><button disabled={busy} onClick={()=>void action(async()=>setResearchCommands(await call(path+'/research')))}>Làm mới trạng thái run</button></div><p className="muted">Dùng cho run được bạn duyệt thủ công trong tab Idea/Run. Với agent tự duyệt, dùng Research pipeline ở trên. Cả hai đường gọi Working hiện có và giữ gate account/quota.</p>
      <form className="stack" onSubmit={e=>{e.preventDefault();void action(async()=>{setBinding(await call(path+'/research/binding/'+encodeURIComponent(runId)));setNotice('Đã đọc approval. Chọn kết quả Reviewer và kiểm tra budget trước khi bắt đầu Working.');});}}><label>Run ID<input required value={runId} onChange={e=>{setRunId(e.target.value);setBinding(null);}}/></label><button disabled={busy}>Đọc approval</button></form>
      {binding&&<div className="stack"><pre>{JSON.stringify(binding,null,2)}</pre><label>Checkpoint đã review<select value={reviewTask} onChange={e=>setReviewTask(e.target.value)}><option value="">Chọn Reviewer task</option>{team.tasks.filter(t=>t.state==='DONE'&&team.spec.seats.find(s=>s.id===t.seat)?.role==='reviewer').map(t=><option key={t.id} value={t.id}>{t.id} · {t.result?.checkpoint?.slice(0,12)}</option>)}</select></label><label>Account (bỏ trống = mặc định)<input value={researchAccount} onChange={e=>setResearchAccount(e.target.value)}/></label><label>Thời hạn CPU session (giây)<input type="number" min={60} max={43200} value={researchTtl} onChange={e=>setResearchTtl(Number(e.target.value))}/></label><button className="primary" disabled={busy||!reviewTask} onClick={()=>void action(async()=>{const reviewer=team.tasks.find(t=>t.id===reviewTask);const body={...binding,review_task_id:reviewTask,checkpoint:reviewer?.result?.checkpoint,ttl_seconds:researchTtl,account:researchAccount||null,accelerator:'cpu'};const intent=await teamIntent(selected+':research',body);await call(path+'/research','POST',{...body,request_id:intent.id});setResearchCommands(await call(path+'/research'));setNotice('Working đã nhận lệnh. Theo dõi kết quả trong tab Run.');})}>Bắt đầu Working theo approval</button></div>}
      {researchCommands.map(c=><article key={c.request_id}><p><strong>{c.run.state}</strong> · {c.state} · {c.request_id}</p><a href={`/?project=${c.binding.project_id}&run=${c.binding.run_id}`}>Mở run ↗</a>{c.state==='UNKNOWN'&&<div className="actions"><button disabled={busy} onClick={()=>void action(async()=>{await call(path+'/research/'+c.request_id+'/reconcile','POST');setResearchCommands(await call(path+'/research'));})}>Đối soát Working intent</button><button disabled={busy} onClick={()=>void action(async()=>{await call(path+'/research/'+c.request_id+'/reconcile?retry=true','POST');setResearchCommands(await call(path+'/research'));})}>Đối soát rồi retry nếu chưa chạy</button></div>}</article>)}
    </section>}
    <section className="panel"><div className="panel-head"><h2>Usage & resource limits</h2><button disabled={busy} onClick={()=>void action(async()=>{setUsage(await call(path+'/telemetry'));setResources(await call(path+'/resources'));})}>Cập nhật usage</button></div><p className="muted">Usage không được provider báo sẽ hiển thị null. Coding team và quota Kaggle được quản lý riêng.</p>{usage!==null&&<pre>{JSON.stringify(usage,null,2)}</pre>}{can('workspace')&&<details><summary>Resource pools</summary><p className="muted">Giới hạn số phiên coding đồng thời của các seat dùng chung pool. Pool được scheduler kiểm tra trước khi cấp lease.</p><label>CodingResource JSON<textarea className="team-code" rows={5} value={resourceJson} onChange={e=>setResourceJson(e.target.value)}/></label><button disabled={busy||Boolean(team.enabled)} onClick={()=>void action(async()=>{const spec=JSON.parse(resourceJson);await call(path+'/resources/'+encodeURIComponent(spec.id),'PUT',spec);setResources(await call(path+'/resources'));})}>Lưu pool</button>{resources.map(r=><p key={r.id}>{r.name} · {r.seat_ids.join(', ')} · tối đa {r.max_parallel} <button disabled={busy||Boolean(team.enabled)} onClick={()=>void action(async()=>{await call(path+'/resources/'+r.id,'DELETE');setResources(await call(path+'/resources'));})}>Xóa pool</button></p>)}</details>}{admin&&<details><summary>CLI / TUI / MCP credential cho {seat}</summary><p className="muted">Credential một giờ chỉ có quyền đọc, gửi thông điệp và giao coding task cho seat này; không có quyền approve hay chạy research.</p><button disabled={busy} onClick={()=>void action(async()=>{const result=await call<{token:string}>(seatPath+'/credential','POST');setAgentCredential(result.token);})}>Tạo credential</button>{agentCredential&&<><code>{agentCredential}</code><p>Đặt AI_SCIENTIST_AGENT_DEVICE_TOKEN trong môi trường riêng của client, rồi chạy tools/agent_management.py teams, tui hoặc mcp.</p><button onClick={()=>setAgentCredential('')}>Ẩn credential</button></>}</details>}</section>
    <section className="panel"><h2>Team chatroom</h2><div className="team-chat">{messages.map(m=><article key={m.id}><strong>{m.sender} → {m.recipient}</strong><p>{m.body}</p></article>)}</div>{can('message')&&<form className="stack" onSubmit={e=>{e.preventDefault();void action(async()=>{await call(path+'/messages','POST',{sender,recipient,body:message});setMessage('');await refresh();});}}><div className="actions"><label>Người gửi<select value={sender} onChange={e=>setSender(e.target.value)}>{team.spec.seats.map(s=><option key={s.id}>{s.id}</option>)}</select></label><label>Người nhận<select value={recipient} onChange={e=>setRecipient(e.target.value)}><option value="*">Broadcast</option>{team.spec.seats.map(s=><option key={s.id}>{s.id}</option>)}</select></label></div><label>Thông điệp<textarea required value={message} onChange={e=>setMessage(e.target.value)}/></label><button disabled={busy}>Gửi</button></form>}</section>
    <section className="panel"><h2>Events / output</h2><div className="team-event-log">{events.map(e=><article key={e.id}><small>#{e.id} · {e.timestamp} · {e.seat_id}</small><strong>{e.kind}</strong><pre>{typeof e.data.text==='string'?e.data.text:JSON.stringify(e.data,null,2)}</pre></article>)}</div></section>
    </>}
    {admin&&<section className="panel"><h2>Slack opt-in</h2><p className="muted">Token được cấu hình riêng trên backend qua AI_SCIENTIST_SLACK_TOKEN. Mỗi thông điệp chỉ được gửi khi bạn bấm Gửi.</p><div className="actions"><button disabled={busy} onClick={()=>void action(async()=>{const s=await call<{enabled:boolean;channel:string|null}>('/integrations/slack');setSlackEnabled(s.enabled);setSlackChannel(s.channel||'');})}>Đọc cấu hình</button><label><input type="checkbox" checked={slackEnabled} onChange={e=>setSlackEnabled(e.target.checked)}/>Bật Slack</label></div><label>Channel ID<input value={slackChannel} onChange={e=>setSlackChannel(e.target.value)}/></label><button disabled={busy} onClick={()=>void action(async()=>{await call('/integrations/slack','PUT',{enabled:slackEnabled,channel:slackChannel||null});setNotice('Đã lưu cấu hình Slack');})}>Lưu cấu hình</button><label>Nội dung<textarea value={slackText} onChange={e=>setSlackText(e.target.value)}/></label><button disabled={busy||!slackEnabled||!slackText.trim()} onClick={()=>void action(async()=>{await call('/integrations/slack/messages','POST',{text:slackText});setSlackText('');setNotice('Đã gửi thông điệp Slack');})}>Gửi thông điệp này</button></section>}
    {admin&&<section className="panel"><div className="panel-head"><h2>Thiết bị cá nhân</h2><div className="actions"><button disabled={busy||!selected} onClick={()=>void action(async()=>setPair(await call('/pair','POST',{rig_ids:[selected],scopes:['read','task','message','workspace','permission',...(pairResearch?['research']:[])]})))}>Tạo mã cho team này</button><button disabled={busy} onClick={()=>void action(async()=>setDevices(await call('/devices')))}>Xem thiết bị</button></div></div><label><input type="checkbox" checked={pairResearch} onChange={e=>setPairResearch(e.target.checked)}/>Cho thiết bị này bắt đầu/dừng workflow và trả lời các bước chờ người duyệt</label><p className="muted">Trên thiết bị khác, mở Settings → Multi-agent qua HTTPS private đã cấu hình, rồi nhập Pairing ID và mã. Mã dùng một lần, hết hạn sau 5 phút.</p>{pair&&<div className="alert"><p>Pairing ID: <code>{pair.pairing_id}</code></p><p>Mã: <code>{pair.code}</code></p><p>Hết hạn: {pair.expires_at}</p></div>}{devices.map(d=><article key={d.id}><strong>{d.name}</strong><p>{d.scopes.join(', ')} · {d.revoked?'Đã thu hồi':'Còn hiệu lực'}</p><button disabled={busy||d.revoked} onClick={()=>void action(async()=>{await call('/devices/'+d.id,'DELETE');setDevices(await call('/devices'));})}>Thu hồi</button></article>)}</section>}
    </>}
  </main></>;
}
