import {useEffect,useState} from 'react';
import {Harness,Snapshot,teamIntent} from './teamApi';

const stages=[['ideation','Nghĩ idea'],['proposal','Lập proposal'],['approval','Duyệt proposal'],['execution','Thực thi một run'],['draft','Draft'],['tuning','Tuning'],['research','Research'],['ablation','Ablation'],['analysis','Phân tích'],['summary','Summary'],['report','Report'],['plots','Plots'],['writeup','Viết bài'],['review','Review']] as const;
type Binding={actor:'human'|'agent';seat:string;ask:boolean};
type Spec={goal:string;mode:'training_research'|'etc';benchmark_id:string|null;resource_ids:string[];desired_output:string;stages:Record<string,Binding>;allow_agent_approval:boolean;max_runs:number;ttl_seconds:number;execution_seconds:number;max_agent_calls:number;output_bytes:number;accelerator:string;account:string;research:{summary:boolean;report:boolean;plots:boolean;writeup:string;review:boolean;seeds:number[];seed_stages:number[];reflections:number};search:{enabled:boolean;stage_iterations:number[];num_drafts:number;debug_prob:number;max_debug_depth:number}};
type Input={id:string;stage:string;state:string;prompt:{kind:string;candidate?:unknown;prompt?:unknown;schema?:unknown}};
type Flow={id:string;project_id?:string;spec:Spec;state:{status:string;stage:string;iteration:number;calls:number;runs:string[];run_id:string|null;events:{stage:string;kind:string;at:string;seat?:string;task_id?:string}[];error?:string};inputs?:Input[]};
type Options={project_id:string;resources:{id:string;title:string}[];benchmarks:{id:string;title?:string;name?:string}[];accounts:{account:string;username:string;configured:boolean}[]};
type Props={team:Snapshot;harnesses:Harness[];canResearch:boolean;call:<T>(path:string,method?:string,body?:unknown)=>Promise<T>;updateSeat:(id:string,key:string,value:unknown)=>Promise<void>;onSelectSeat:(id:string)=>void;canConfigureAgents:boolean};
function defaults(team:Snapshot):Spec{
  return {goal:'',mode:'training_research',benchmark_id:null,resource_ids:[],desired_output:'',stages:Object.fromEntries(stages.map(([id])=>[id,{actor:['ideation','approval'].includes(id)?'human':'agent',seat:team.spec.seats.find(s=>s.id===id)?.id||team.spec.seats[0].id,ask:false}])),allow_agent_approval:false,max_runs:1,ttl_seconds:600,execution_seconds:480,max_agent_calls:40,output_bytes:1000000,accelerator:'cpu',account:'jhin_access_token.txt',research:{summary:false,report:false,plots:false,writeup:'none',review:false,seeds:[],seed_stages:[2,3],reflections:1},search:{enabled:false,stage_iterations:[1,1,1,1],num_drafts:1,debug_prob:.5,max_debug_depth:1}};
}
function HumanProposalInput({spec,disabled,submit}:{spec:Spec;disabled:boolean;submit:(result:unknown)=>void}){
  const [objective,setObjective]=useState(spec.goal),[steps,setSteps]=useState(''),[outputs,setOutputs]=useState('');
  return <div className="stack"><label>Mục tiêu proposal<textarea rows={3} value={objective} onChange={e=>setObjective(e.target.value)}/></label><label>Các bước thực hiện (mỗi dòng một bước)<textarea rows={4} value={steps} onChange={e=>setSteps(e.target.value)}/></label><label>Đầu ra mong muốn (mỗi dòng một mục)<textarea rows={2} value={outputs} onChange={e=>setOutputs(e.target.value)}/></label><p className="muted">Dùng benchmark và context đã chọn. Budget: {spec.execution_seconds}s, {spec.output_bytes} bytes.</p><button disabled={disabled||!objective.trim()||!steps.trim()} onClick={()=>submit({needs_clarification:false,questions:[],paraphrase:objective,objective,implementation_steps:steps.split('\n').map(s=>s.trim()).filter(Boolean),expected_outputs:outputs.split('\n').map(s=>s.trim()).filter(Boolean),data_refs:spec.resource_ids,budget:{execution_seconds:spec.execution_seconds,output_bytes:spec.output_bytes},research:spec.mode==='training_research'?spec.research:null})}>Gửi proposal và tiếp tục</button></div>;
}
export default function ResearchWorkflowPanel({team,harnesses,canResearch,call,updateSeat,onSelectSeat,canConfigureAgents}:Props){
  const [spec,setSpec]=useState(()=>defaults(team)),[flows,setFlows]=useState<Flow[]>([]),[flow,setFlow]=useState<Flow|null>(null),[options,setOptions]=useState<Options|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[answers,setAnswers]=useState<Record<string,string>>({}),[ideas,setIdeas]=useState<Record<string,{title:string;text:string}>>({});
  const base='/teams/'+team.id;
  async function action(work:()=>Promise<void>){setBusy(true);setError('');try{await work();}catch(e){setError(String(e instanceof Error?e.message:e));}finally{setBusy(false);}}
  useEffect(()=>{setFlow(null);setSpec(defaults(team));setFlows([]);setOptions(null);setError('');setAnswers({});setIdeas({});if(!team.spec.project_id)return;void call<Options>(base+'/workflow-options').then(setOptions).catch(e=>setError(String(e.message)));void call<Flow[]>(base+'/workflows').then(setFlows).catch(e=>setError(String(e.message)));},[team.id,team.spec.project_id]);
  useEffect(()=>{if(!flow)return;let stopped=false;const timer=setInterval(()=>void call<Flow>(base+'/workflows/'+flow.id).then(value=>{if(!stopped)setFlow(value);}).catch(e=>{if(!stopped)setError(String(e.message));}),2000);return()=>{stopped=true;clearInterval(timer);};},[flow?.id,team.id]);
  useEffect(()=>{if(!team.spec.project_id)return;let stopped=false;const timer=setInterval(()=>void call<Flow[]>(base+'/workflows').then(value=>{if(!stopped)setFlows(value);}).catch(e=>{if(!stopped)setError(String(e.message));}),5000);return()=>{stopped=true;clearInterval(timer);};},[team.id,team.spec.project_id]);
  const visible=flow?.spec||spec;
  const set=(patch:Partial<Spec>)=>setSpec(s=>({...s,...patch}));
  const stageSet=(id:string,patch:Partial<Binding>)=>setSpec(s=>({...s,stages:{...s.stages,[id]:{...s.stages[id],...patch}}}));
  async function respond(input:Input,result:unknown){await call(base+'/workflows/'+flow!.id+'/inputs/'+input.id,'POST',{result});setFlow(await call<Flow>(base+'/workflows/'+flow!.id));}
  function badge(id:string){const last=flow?.state.events.filter(e=>e.stage===id).at(-1);if(flow?.state.stage===id&&flow.state.status==='WAITING')return 'Chờ bạn';if(last?.kind==='agent_queued')return flow?.state.status==='PAUSED'?'Tạm dừng':flow?.state.status==='UNKNOWN'?'Chưa rõ kết quả':'Đang xử lý';if(last?.kind==='agent_completed'||last?.kind==='human_completed')return 'Đã xong';return 'Chưa chạy';}
  return <section className="panel research-workflow"><div className="panel-head"><div><span className="eyebrow">RESEARCH PIPELINE</span><h2>Mỗi giai đoạn, một người hoặc agent</h2><p className="muted">Cấu hình người thực hiện và harness/model cho từng stage. Chọn điểm cần bạn duyệt hoặc giao quyền tự chạy trong hạn mức.</p></div>{flow&&<button onClick={()=>{setFlow(null);setSpec(defaults(team));}}>Cấu hình mới</button>}</div>
    {!team.spec.project_id?<p className="alert">Tạo team bằng template Research pipeline và chọn Project để sử dụng luồng này.</p>:<>
    {error&&<p role="alert" className="alert error">{error}</p>}
    {flows.length>0&&<label>Workflow đã lưu<select value={flow?.id||''} onChange={e=>void action(async()=>setFlow(e.target.value?await call<Flow>(base+'/workflows/'+e.target.value):null))}><option value="">Tạo cấu hình mới</option>{flows.map(f=><option key={f.id} value={f.id}>{f.spec.goal.slice(0,60)} · {f.state.status}</option>)}</select></label>}
    {!flow&&canResearch&&<div className="stack"><div className="actions"><button type="button" onClick={()=>set({stages:Object.fromEntries(stages.map(([id])=>[id,{...spec.stages[id],actor:['ideation','approval'].includes(id)?'human':'agent',ask:false}])),allow_agent_approval:false})}>Ask for approval</button><button type="button" onClick={()=>set({stages:Object.fromEntries(stages.map(([id])=>[id,{...spec.stages[id],actor:'agent',ask:false}])),allow_agent_approval:true})}>Full auto</button></div>
      <label>Mục tiêu nghiên cứu<textarea required rows={3} value={spec.goal} onChange={e=>set({goal:e.target.value})} placeholder="Agent cần tìm và kiểm chứng điều gì?"/></label>
      <div className="team-create"><label>Loại công việc<select value={spec.mode} onChange={e=>set({mode:e.target.value as Spec['mode'],search:{...spec.search,enabled:false}})}><option value="training_research">Training / Research</option><option value="etc">Etc</option></select></label>{spec.mode==='training_research'?<label>Benchmark<select value={spec.benchmark_id||''} onChange={e=>set({benchmark_id:e.target.value||null})}><option value="">Chọn benchmark đã hoàn tất</option>{options?.benchmarks.map(b=><option key={b.id} value={b.id}>{b.title||b.name||b.id}</option>)}</select></label>:<label>Đầu ra cần nhận<input value={spec.desired_output} onChange={e=>set({desired_output:e.target.value,benchmark_id:null})}/></label>}<label>Account Kaggle<select value={spec.account} onChange={e=>set({account:e.target.value})}><option value="">Chọn account</option>{options?.accounts.filter(a=>a.configured).map(a=><option key={a.account} value={a.account}>{a.username}</option>)}</select></label></div>
      <details><summary>Context từ Library</summary>{options?.resources.map(source=><label key={source.id}><input type="checkbox" checked={spec.resource_ids.includes(source.id)} onChange={e=>set({resource_ids:e.target.checked?[...spec.resource_ids,source.id]:spec.resource_ids.filter(id=>id!==source.id)})}/>{source.title}</label>)}</details>
    </div>}
    <div className="workflow-map" aria-label="Research stage activity">{stages.filter(([id])=>['ideation','proposal','approval'].includes(id)||id==='execution'&&!visible.search.enabled||['draft','tuning','research','ablation','analysis'].includes(id)&&visible.search.enabled||visible.mode==='training_research'&&(id==='summary'&&visible.research.summary||id==='report'&&visible.research.report||id==='plots'&&visible.research.plots||id==='writeup'&&visible.research.writeup!=='none'||id==='review'&&visible.research.review)).map(([id,label])=>{const binding=visible.stages[id];const seat=team.spec.seats.find(s=>s.id===binding.seat);return <button type="button" onClick={()=>onSelectSeat(binding.seat)} key={id} className={'workflow-node '+(flow?.state.stage===id?'current'+(flow.state.status==='RUNNING'?' running':''):'')}><span className="eyebrow">{label}</span><strong>{binding.actor==='human'?'Bạn':binding.seat}</strong><small>{binding.actor==='human'?'Human':`${seat?.harness||''} · ${seat?.model||'provider default'}`}</small><span className="state-tag">{badge(id)}</span></button>;})}</div>
    {!flow&&canResearch&&<><div className="workflow-stage-list">{stages.map(([id,label])=>{const binding=spec.stages[id];const seat=team.spec.seats.find(s=>s.id===binding.seat);const hs=harnesses.find(h=>h.spec.id===seat?.harness);return <div className="workflow-stage-row" key={id}><strong>{label}</strong><label>Thực hiện<select value={binding.actor} onChange={e=>stageSet(id,{actor:e.target.value as Binding['actor']})}><option value="human">Human</option><option value="agent">Agent</option></select></label><label>Agent<select value={binding.seat} onChange={e=>stageSet(id,{seat:e.target.value})}>{team.spec.seats.map(s=><option key={s.id}>{s.id}</option>)}</select></label>{binding.actor==='agent'&&seat&&<><label>Harness<select value={seat.harness} disabled={busy||Boolean(team.enabled)||!canConfigureAgents} onChange={e=>void action(()=>updateSeat(seat.id,'harness',e.target.value))}>{harnesses.map(h=><option key={h.spec.id}>{h.spec.id}</option>)}</select></label><label>Model<input key={seat.id+seat.model} defaultValue={seat.model||''} list={'workflow-models-'+id} disabled={busy||Boolean(team.enabled)||!canConfigureAgents} onBlur={e=>{if((e.target.value||null)!==seat.model)void action(()=>updateSeat(seat.id,'model',e.target.value||null));}}/><datalist id={'workflow-models-'+id}>{hs?.spec.models.map(m=><option key={m}>{m}</option>)}</datalist></label><label className="workflow-ask"><input type="checkbox" checked={binding.ask} onChange={e=>stageSet(id,{ask:e.target.checked})}/>Chờ tôi duyệt kết quả</label><details className="workflow-stage-instructions"><summary>Instructions · {seat.id}</summary><textarea rows={3} key={seat.id+seat.instructions} defaultValue={seat.instructions} disabled={busy||Boolean(team.enabled)||!canConfigureAgents} onBlur={e=>{if(e.target.value!==seat.instructions)void action(()=>updateSeat(seat.id,'instructions',e.target.value));}}/></details></>}</div>;})}</div>
      <details><summary>Giới hạn tự chạy và đầu ra</summary><div className="team-create">{([['max_runs','Số run tối đa'],['max_agent_calls','Lượt agent tối đa'],['ttl_seconds','Thời hạn phiên (giây)'],['execution_seconds','Budget thực thi (giây)'],['output_bytes','Output tối đa (bytes)']] as const).map(([key,label])=><label key={key}>{label}<input type="number" min={1} value={spec[key]} onChange={e=>set({[key]:Number(e.target.value)})}/></label>)}<label>Accelerator<select value={spec.accelerator} onChange={e=>set({accelerator:e.target.value})}>{['cpu','NvidiaT4','TpuV5E8','TpuV6E8'].map(a=><option key={a}>{a}</option>)}</select></label></div>
      <label><input type="checkbox" checked={spec.allow_agent_approval} onChange={e=>set({allow_agent_approval:e.target.checked})}/>Cho phép agent duyệt proposal trong đúng project, benchmark và các hạn mức trên.</label>
      <div className="actions">{(['summary','report','plots','review'] as const).map(key=><label key={key}><input type="checkbox" checked={spec.research[key]} onChange={e=>set({research:{...spec.research,[key]:e.target.checked}})}/>{key}</label>)}<label>PDF<select value={spec.research.writeup} onChange={e=>set({research:{...spec.research,writeup:e.target.value}})}><option value="none">Không</option><option value="icbinb">ICBINB</option><option value="normal">ICML</option></select></label></div>
      {spec.mode==='training_research'&&<><label><input type="checkbox" checked={spec.search.enabled} onChange={e=>set({search:{...spec.search,enabled:e.target.checked}})}/>Dùng experiment manager của AI Scientist: Draft → Tuning → Research → Ablation</label>{spec.search.enabled&&<div className="team-create">{['Draft','Tuning','Research','Ablation'].map((label,i)=><label key={label}>{label}: số bước tối đa<input type="number" min={1} value={spec.search.stage_iterations[i]} onChange={e=>set({search:{...spec.search,stage_iterations:spec.search.stage_iterations.map((n,j)=>i===j?Number(e.target.value):n)}})}/></label>)}</div>}</>}
      </details><button className="primary" disabled={busy||!spec.goal.trim()} onClick={()=>void action(async()=>{const intent=await teamIntent(team.id+':workflow',spec);const request_id=intent.id.replaceAll('-','');const created=await call<Flow>(base+'/workflows','POST',{request_id,spec});intent.ack();setFlow(await call<Flow>(base+'/workflows/'+created.id));setFlows(await call<Flow[]>(base+'/workflows'));})}>Lưu workflow và phạm vi ủy quyền</button></>}
    {flow&&<><p><strong>{flow.spec.goal}</strong></p><div className="panel-head"><p><strong>{flow.state.status}</strong> · {flow.state.iteration}/{flow.spec.max_runs} run · {flow.state.calls}/{flow.spec.max_agent_calls} lượt agent</p>{canResearch&&<div className="actions"><button className="primary" disabled={busy||['RUNNING','WAITING','DONE','UNKNOWN'].includes(flow.state.status)} onClick={()=>void action(async()=>setFlow(await call<Flow>(base+'/workflows/'+flow.id+'/start','POST')))}>Bắt đầu / Tiếp tục</button><button disabled={busy||!['RUNNING','WAITING'].includes(flow.state.status)} onClick={()=>void action(async()=>setFlow(await call<Flow>(base+'/workflows/'+flow.id+'/pause','POST')))}>Dừng workflow</button></div>}</div>{flow.state.error&&<p className="alert error">{flow.state.error}</p>}{canResearch&&flow.state.status==='UNKNOWN'&&<button disabled={busy} onClick={()=>void action(async()=>setFlow(await call<Flow>(base+'/workflows/'+flow.id+'/reconcile','POST')))}>Đối soát workflow trước khi tiếp tục</button>}
      {flow.inputs?.filter(i=>i.state==='PENDING').map(input=><div className="workflow-human" key={input.id}><h3>{stages.find(([id])=>id===input.stage)?.[1]} · Chờ bạn</h3><details><summary>Xem yêu cầu và dữ liệu</summary><pre>{JSON.stringify(input.prompt,null,2)}</pre></details>{input.prompt.kind==='review'||input.stage==='approval'?<div className="actions"><button disabled={busy||!canResearch||flow.state.status!=='WAITING'} onClick={()=>void action(()=>respond(input,{approve:true,reason:'Operator approved this exact candidate'}))}>Duyệt</button><button disabled={busy||!canResearch||flow.state.status!=='WAITING'} onClick={()=>void action(()=>respond(input,{approve:false,reason:'Operator rejected this candidate'}))}>Từ chối</button></div>:input.stage==='ideation'?<><label>Tên idea<input value={ideas[input.id]?.title||''} onChange={e=>setIdeas(v=>({...v,[input.id]:{title:e.target.value,text:v[input.id]?.text||''}}))}/></label><label>Giả thuyết và mục tiêu<textarea rows={4} value={ideas[input.id]?.text||''} onChange={e=>setIdeas(v=>({...v,[input.id]:{title:v[input.id]?.title||'',text:e.target.value}}))}/></label><button disabled={busy||!canResearch||flow.state.status!=='WAITING'||!ideas[input.id]?.title||!ideas[input.id]?.text} onClick={()=>void action(()=>respond(input,ideas[input.id]))}>Gửi idea và tiếp tục</button></>:input.stage==='proposal'?<HumanProposalInput key={input.id} spec={flow.spec} disabled={busy||!canResearch||flow.state.status!=='WAITING'} submit={result=>void action(()=>respond(input,result))}/>:<><label>Kết quả JSON<textarea rows={5} value={answers[input.id]??(input.stage==='ideation'?' {"title":"Ý tưởng của tôi","text":"Mô tả giả thuyết cần kiểm chứng"}':'{}')} onChange={e=>setAnswers(old=>({...old,[input.id]:e.target.value}))}/></label><button disabled={busy||!canResearch||flow.state.status!=='WAITING'} onClick={()=>void action(()=>respond(input,JSON.parse(answers[input.id]??(input.stage==='ideation'?'{"title":"Ý tưởng của tôi","text":"Mô tả giả thuyết cần kiểm chứng"}':'{}'))))}>Gửi và tiếp tục</button></>}</div>)}
      <div className="actions">{[...flow.state.runs,...(flow.state.run_id?[flow.state.run_id]:[])].map(run=><a key={run} href={`/?project=${options?.project_id}&run=${run}`}>Mở run {run.slice(0,8)} ↗</a>)}</div>
      <details><summary>Hoạt động và handoff</summary>{flow.state.events.slice(-20).reverse().map((event,i)=><p key={i}><time>{new Date(event.at).toLocaleTimeString()}</time> · {event.stage} · {event.kind} {event.seat&&'· '+event.seat}</p>)}</details>
    </>}
    </>}
  </section>;
}
